In [2]:
import numpy as np

Array Operations

1. Arithmetic Operations

In [3]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])


In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [10]:
l = [10, 20, 30, 40]
arr = np.array(l)


In [11]:
arr + 10

array([20, 30, 40, 50])

In [12]:
arr2  = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [14]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow copy

In [15]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
a[4:6] *10

array([50, 60])

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
a
b = a.copy()

In [21]:
b[0] = 90

In [22]:
b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [24]:
A = np.array([[1,2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [25]:
A

array([[1, 2],
       [3, 4]])

In [26]:
B

array([[5, 6],
       [7, 8]])

In [27]:
A*B

array([[ 5, 12],
       [21, 32]])

In [28]:
A @ B

array([[19, 22],
       [43, 50]])

In [30]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [32]:
A

array([[1, 2],
       [3, 4]])

In [33]:
A.T

array([[1, 3],
       [2, 4]])

Advance Array Manipluation

In [34]:
## Stacking arrays

In [35]:
A

array([[1, 2],
       [3, 4]])

In [36]:
B

array([[5, 6],
       [7, 8]])

In [41]:
p = np.array([1, 2, 3, 4])
q = np.array([5, 6, 7, 8])

In [42]:
np.vstack((p, q))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
np.hstack((p, q))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np.column_stack((p, q))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [45]:
## Splitting arrays

In [46]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [48]:
np.vsplit(c, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]