In [1]:
import numpy as np

NumPy Indexing And Slicing of Vectors

In [2]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[9] #indexing returns the value at the specified index in the array.

np.int64(20)

In [5]:
arr[1:5] #slicing returns a new array that contains a subset of the elements from the original array.

array([12, 13, 14, 15])

In [6]:
arr[:5] 

array([11, 12, 13, 14, 15])

In [7]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[3::2] #start at index 3 and return every second element from that point onward.

array([14, 16, 18, 20])

NumPy Indexing and Slicing of Matrix

In [13]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr[5,4]

np.int64(30)