In [2]:
import numpy as np

Valid Sudoku

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [ ]:
b = np.sum(s, axis = 1)    #Rows Axis will be 1 , Columns Axis will be 0

#b == 45

for i in b:
    if i != 45:
        print("Not a valid Sudoku")
        break
    else:
        print("Valid Sudoku")


Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku


In [10]:
c = np.sum(s, axis = 0)    #Rows Axis will be 1 , Columns Axis will be 0

#b == 45

for i in b:
    if i != 45:
        print("Not a valid Sudoku")
        break
    else:
        print("Valid Sudoku")


Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku


In [ ]:
# s[0:3, 0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
# s[0:3, 3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [16]:
for i in range(0, 9, 3): #rows
    for j in range(0, 9, 3): #columns
        n = s[i:i+3,  j:j+3]
        print(n.sum())


45
45
45
45
45
45
45
45
45


General Questions

In [4]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [17]:
#Get the shape of the matrix

data.shape #No Brackets needed for shape, it is an instance attribute.

(5, 3)

In [18]:
#Find the average age of students.

np.mean(data[:, 0]) #Average of the first column (Age)

np.float64(18.4)

In [19]:
#Extract Math marks of all students.

data[:, 1] #Extracting the second column (Math Marks)

array([85, 92, 76, 65, 90])

In [20]:
#Find the highest Science mark.

np.max(data[:, 2]) #Maximum of the third column (Science Marks)

np.int64(95)

In [23]:
#Get details of the student who scored more than 90 in Math.

data[data[:, 1] > 90] #This will return a boolean array

array([[19, 92, 88]])

In [28]:
data

array([[ 18,  95,  78],
       [ 19, 102,  88],
       [ 17,  86,  95],
       [ 18,  75,  70],
       [ 20, 100,  85]])

In [29]:
#Increase Math marks of all students by 5.

data[:, 1] += 5
data


array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [ 18,  80,  70],
       [ 20, 105,  85]])

In [32]:
#Find how many students are younger than 19.

len(data[data[:, 0] < 19])

3

In [33]:
#Calculate the average marks in each subject (column-wise mean).

np.mean(data[:,1:], axis=0)
data

array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [ 18,  80,  70],
       [ 20, 105,  85]])

In [34]:
#Get data of students who scored at least 80 in both subjects.

data[(data[:, 1] >= 80) & (data[:,2] >= 80)]


array([[ 19, 107,  88],
       [ 17,  91,  95],
       [ 20, 105,  85]])

In [35]:
#Replace all Science marks < 75 with 0.

data

array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [ 18,  80,  70],
       [ 20, 105,  85]])

In [37]:
data[:, 2][data[:,2] < 75] = 0 
data

array([[ 18, 100,  78],
       [ 19, 107,  88],
       [ 17,  91,  95],
       [ 18,  80,   0],
       [ 20, 105,  85]])