In [1]:
import numpy as np

Basic Array Creation

In [5]:
arr = np.array([1,2,3,4,5])
(arr)

array([1, 2, 3, 4, 5])

In [7]:
a = [1,2,3,4,"Hello"]
a

[1, 2, 3, 4, 'Hello']

In [8]:
np.array(a)

array(['1', '2', '3', '4', 'Hello'], dtype='<U21')

In [9]:
l = [[1,2,3,], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Funtion

In [14]:
arr = np.arange(1,11, 2)
print(arr)

[1 3 5 7 9]


In [17]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
arr = np.linspace(1, 10, 5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Random Generation Funtion: Allows us to Generate some Random Numbers

In [20]:
np.random.rand(5)

array([0.96056206, 0.21439671, 0.28321587, 0.15064326, 0.90511758])

In [23]:
np.random.randint(10,20, 10)

array([19, 18, 13, 17, 14, 14, 13, 16, 11, 11], dtype=int32)

Array Attributes

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
#There is not a shape attribute for lists, but there is one for numpy arrays. 

# The shape attribute returns a tuple representing the dimensions of the array. and there is no brackets after when calling the attribute

arr.shape


(3, 3)

In [ ]:
#Shows the total number of elements in the array. 

arr.size

9

In [28]:
#The dtype attribute returns the data type of the elements in the array.

arr.dtype

dtype('int64')

Array Methods

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#min() function returns the minimum value in the array. 

arr.min()

np.int64(1)

In [ ]:
#max() function returns the maximum value in the array.

arr.max()

np.int64(9)

In [ ]:
#sum() function returns the sum of all the elements in the array.

arr.sum()

np.int64(45)

In [36]:
np.sum(arr, axis=0) #sum of each column

array([12, 15, 18])

In [37]:
np.sum(arr, axis=1) #sum of each row

array([ 6, 15, 24])

In [ ]:
arr.mean() #mean() function returns the average of all the elements in the array.

np.float64(5.0)

In [ ]:
arr.std() #std() function returns the standard deviation of the elements in the array.

np.float64(2.581988897471611)

In [40]:
arr.argmax() #argmax() function returns the index of the maximum value in the array.

np.int64(8)

In [41]:
arr.argmin() #argmin() function returns the index of the minimum value in the array.

np.int64(0)

Reshaping and resizing

In [43]:
arr = np.arange(1, 31) #arrange() function returns an array with evenly spaced values within a given range.

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
arr.reshape(6, 5) #reshape() function returns an array with a new shape without changing its data.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])